Repository ucsb-cs156-s25/proj-frontiers-s25-11, pull requests merged in 2025-05, with the labels that each got.

#27 tr - add PUT (update) method for RosterStudent Controller
  src/main/java/edu/ucsb/cs156/frontiers/controllers/RosterStudentsController.java
  src/main/java/edu/ucsb/cs156/frontiers/dtos/RosterStudentUpdateDTO.java
  src/main/java/edu/ucsb/cs156/frontiers/errors/InvalidRequestException.java
  src/main/java/edu/ucsb/cs156/frontiers/repositories/RosterStudentRepository.java
  src/test/java/edu/ucsb/cs156/frontiers/controllers/RosterStudentsControllerTests.java
Labels: 10, Merge Candidate-CI

#28 sl - create Admin table
  src/main/java/edu/ucsb/cs156/frontiers/entities/Admin.java
  src/main/java/edu/ucsb/cs156/frontiers/repositories/AdminRepository.java
  src/main/resources/db/migration/changes/007-Admins-create.json
Labels: Ready-For-Staff

#29 ws - added instructor table files
  src/main/java/edu/ucsb/cs156/frontiers/entities/Instructor.java
  src/main/java/edu/ucsb/cs156/frontiers/repositories/InstructorRepository.java
  src/main/resources/db/migration/changes/008-Instructors-create.json
Labels: 5, Merge Candidate-CI

#32 js - fixed errors for Jobs Controller Detailed Tests
  src/test/java/edu/ucsb/cs156/frontiers/controllers/JobsControllerDetailedTests.java
Labels: 5, Merge Candidate-CI

#33 sd - Admin POST and GET operations
  src/main/java/edu/ucsb/cs156/frontiers/controllers/AdminsController.java
  src/main/java/edu/ucsb/cs156/frontiers/entities/Admin.java
  src/test/java/edu/ucsb/cs156/frontiers/controllers/AdminsControllerTests.java
Labels: 10, Merge Candidate-CI

#39 lm- POST and GET for Instructors Table
  src/main/java/edu/ucsb/cs156/frontiers/controllers/InstructorsController.java
  src/test/java/edu/ucsb/cs156/frontiers/controllers/InstructorsControllerTests.java
Labels: 10

#38 sl - add table component for RosterStudents(storybook only)
  frontend/src/fixtures/rosterStudentsFixtures.js
  frontend/src/main/components/RosterStudents/RosterStudentsTable.js
  frontend/src/stories/components/RosterStudents/RosterStudentTable.stories.js
  frontend/src/tests/components/RosterStudents/RosterStudentsTable.test.js
Labels: 10

#34 js - added backend method for students to see courses they appear on roster of and status
  src/main/java/edu/ucsb/cs156/frontiers/controllers/CoursesController.java
  src/test/java/edu/ucsb/cs156/frontiers/controllers/CoursesControllerTests.java
Labels: 10

#41 lm - instructors delete
  src/main/java/edu/ucsb/cs156/frontiers/controllers/InstructorsController.java
  src/test/java/edu/ucsb/cs156/frontiers/controllers/InstructorsControllerTests.java
Labels: 10

#35 sd - Admin DELETE operation implemented
  src/main/java/edu/ucsb/cs156/frontiers/controllers/AdminsController.java
  src/main/java/edu/ucsb/cs156/frontiers/controllers/ApiController.java
  src/test/java/edu/ucsb/cs156/frontiers/controllers/AdminsControllerTests.java
Labels: 10

#37 tr - added startup code to populate Admins table from ADMIN_EMAILS
  src/main/java/edu/ucsb/cs156/frontiers/repositories/AdminRepository.java
  src/main/java/edu/ucsb/cs156/frontiers/startup/FrontiersApplicationRunner.java
  src/main/java/edu/ucsb/cs156/frontiers/startup/FrontiersStartup.java
  src/test/java/edu/ucsb/cs156/frontiers/startup/FrontiersApplicationRunnerTests.java
  src/test/java/edu/ucsb/cs156/frontiers/startup/FrontiersStartupTests.java
Labels: 10

#36 tr - add delete method for RosterStudent controller
  src/main/java/edu/ucsb/cs156/frontiers/controllers/RosterStudentsController.java
  src/main/java/edu/ucsb/cs156/frontiers/entities/Course.java
  src/test/java/edu/ucsb/cs156/frontiers/controllers/RosterStudentsControllerTests.java
Labels: Ready-For-Staff

#44 js - (create a course staff roster) implementation required for roster lookup
  src/main/java/edu/ucsb/cs156/frontiers/controllers/CourseStaffController.java
  src/main/java/edu/ucsb/cs156/frontiers/entities/CourseStaff.java
  src/main/java/edu/ucsb/cs156/frontiers/repositories/CourseStaffRepository.java
  src/main/resources/db/migration/changes/002-create-CourseStaff.json
  src/main/resources/db/migration/changes/009-CourseStaff-add-Email-Orgstat-field.json
  src/test/java/edu/ucsb/cs156/frontiers/controllers/CourseStaffControllerTest.java
  src/test/java/edu/ucsb/cs156/frontiers/controllers/CoursesControllerTests.java
Labels: 10, Merge Candidate-CI, Ready-For-Staff
